artfreedom/apps/main/urls.py
from django.urls import path

from . import views

app_name = "main"


urlpatterns = [
    path("", views.catalog, name="catalog"),
    path("deletechallenge/", views.delete_challenge, name="delete"),
    #path("<int:challenge_id>/", views.challenge, name="challenge"),

]

artfreedom/apps/userprofile/urls.py
 
from django.urls import path

from . import views

app_name = "userprofile"


urlpatterns =[
    path("", views.myprofile, name="myprofile"),
    path("user<int:userid>/", views.profile, name="profile"),
    path("newchallenge/", views.add_new_challenge, name="add_new_challenge"),
]

artfreedom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from main import views
from loginsys import views as login_views
from userprofile import views as user_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.storage import staticfiles_storage

from django.conf import settings
from django.urls import include, re_path

from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.views.generic.base import TemplateView

urlpatterns = [
    path("catalog/", include("main.urls")),
    path("index/", views.index, name="index"),
    path("helper/", views.helper, name="helper"),
    path('admin/', admin.site.urls),
    #path("challenge/", include("main.urls")),
    path("challenge/<int:id>/", views.challenge, name="challenge"),
    path("challenge/participate/", views.participate, name="participate"),
    path("registration/", login_views.registration, name="registration"),
    path("login/", login_views.login, name="login"),
    path("profile/", include("userprofile.urls")),
    path("logout/", login_views.logout, name="logout"),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('/imgs/favicon.ico'))
    ),
    path("kickuser/", views.kick_user, name='kick_user'),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
     path(
        "sitemap-1.xml",
        TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml; charset=UTF-8"),
    ),
]
urlpatterns += [
    path('', RedirectView.as_view(url="index/", permanent=True))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#urlpatterns += patterns('',
#   url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),)
	
urlpatterns += staticfiles_urlpatterns()

artfreedom/apps/main/forms.py
from django import forms

class ChallengesFilterForm(forms.Form):
    status1 = forms.BooleanField(required=False, label="Идет набор")
    status2 = forms.BooleanField(required=False, label="Активный")
    status3 = forms.BooleanField(required=False, label="Завершен")

    duration_max = forms.IntegerField(required=False, min_value=1)
    duration_min = forms.IntegerField(required=False, min_value=1)

    def is_form_empty(self):
        is_empty = self.cleaned_data['status1'] | self.cleaned_data['status2'] | self.cleaned_data['status3']
        is_empty = is_empty | (self.cleaned_data['duration_max'] != None)
        is_empty = is_empty | (self.cleaned_data['duration_min'] != None) 
    
    def is_status_filter_empty(self):
        return self.cleaned_data['status1'] | self.cleaned_data['status2'] | self.cleaned_data['status3']

    def is_duration_filter_empty(self):
        return (self.cleaned_data['duration_max']==None) & (self.cleaned_data['duration_min']==None)

    def clean(self):
        self.cleaned_data = super(ChallengesFilterForm, self).clean()
        if self.cleaned_data['duration_min'] == None:
            self.cleaned_data['duration_min'] = 0
        
        if (self.cleaned_data["duration_min"] != None) & (self.cleaned_data["duration_max"] != None):
            if self.cleaned_data["duration_min"] > self.cleaned_data["duration_max"]:
                raise forms.ValidationError("min > max")

    

artfreedom/apps/loginsys/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages

import re
from main.models import User_data

#from django.core.context_processors import csrf


def registration(request):
    template = "main/register.html"
    if request.POST:
        print(request.POST['login'])
        form = UserRegistrationForm(request.POST)
        if form.is_valid() :
            print("form is valid")
            user = User(username=form.cleaned_data['login'])
            user.set_password(form.cleaned_data['password2'])
            user.save()
            userdata = User_data(user=user, contacts=form.cleaned_data['contact'])
            userdata.save()

        else:
            messages.error(request, "Ошибка регистрации. Проверьте введенные дынные")
            HttpResponseRedirect("/registration/", status=422)
        
        messages.add_message(request, messages.SUCCESS, 'Регистрация прошла успешно')
        return HttpResponseRedirect("/login/", )
    else:
        form = UserRegistrationForm()
        return render(request, "loginsys/register.html", {'form': form})



def login(request):
    args = {}
    #args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect("/profile/")
        else:
            args['login_error'] = "Неверный логин или пароль"
            return render(request, 'loginsys/login.html', args)
    else:
        return render(request, "loginsys/login.html", args)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")

class UserRegistrationForm(forms.Form):
    login = forms.CharField(label="Логин", max_length=50)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    contact = forms.CharField(label='Контакты', max_length=200)

    def clean_password2(self):
        print("clean_password2")
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не одинаковые')
        return cd['password2']
    
    def clean_login(self):
        print("clean_login")

        s = self.cleaned_data['login']
        a = re.match("^[\da-zA-Z0-9]+$", s)
        if a:
            return s
        else:
            raise forms.ValidationError('Лишние знаки')



    def is_digit_and_lowercase_only(s): 
        return re.match("^[\da-zA-Z0-9]+$", s)

artfreedom/apps/main/views.py
from django.shortcuts import render, redirect
from .models import Challenge_article, Comment, Challenge_to_User, User_data
from django.http import Http404, HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.contrib import auth
from django.utils import timezone
from enum import Enum, auto
from django.contrib.auth.models import User
from math import ceil
from .forms import ChallengesFilterForm
from django.contrib import messages



def catalog(request):
    latest_challenges_list = []  # Challenge_article.objects.order_by("-pub_date")[:5]
    if request.GET.get("page", False):
        page = request.GET["page"]
    else:
        page = 1
    try:
        form_filter = ChallengesFilterForm(request.GET)
        challenges = Challenge_article.objects
        if form_filter.is_valid():
            if not form_filter.is_duration_filter_empty():
                if form_filter.cleaned_data['duration_max'] == None:
                    challenges = challenges.filter(recruitment_time__gte=form_filter.cleaned_data['duration_min'])
                else:
                    start = form_filter.cleaned_data['duration_min']
                    fin = form_filter.cleaned_data['duration_max']
                    challenges = challenges.filter(recruitment_time__range=(start, fin))

        challenges = challenges.order_by("-pub_date")
        for ch in challenges:
            dic = {
                "name": ch.article_title,
                "start_date": ch.start_date,
                "recruitment_time": ch.recruitment_time,
                "users_count": Challenge_to_User.objects.filter(challenge=ch).count(),
                "id": ch.id,
                "challenge_status": get_challenge_status(ch).value,
                "challenge_status_en": get_challenge_status(ch).name,
            }

            if ch.avatar != "":
                dic["avatar_url"] = ch.avatar
            latest_challenges_list.append(dic)

    except Exception as e:
        return HttpResponseNotFound()

    if form_filter.is_status_filter_empty():
        latest_challenges_list = list(filter(
            is_challenge_has_status(form_filter.cleaned_data['status1'],
            form_filter.cleaned_data['status2'], form_filter.cleaned_data['status3']),
            latest_challenges_list
        ))
    items_on_page = 8
    max_page = ceil(len(latest_challenges_list) / items_on_page)

    latest_challenges_list = latest_challenges_list[
            (int(page) - 1) * items_on_page : items_on_page * int(page)
        ]
    return render(
        request,
        "main/catalog.html",
        {
            "latest_challenges_list": latest_challenges_list,
            "page": {
                "current_page": page,
                "last_page": max_page,
            },
            "filter_form": form_filter,
        },
    )

def  is_challenge_has_status(recruitment, active, finished):
    def func (challenge):
        status = challenge['challenge_status_en']
        if ((status == 'recruitment') & recruitment):
            print("recruitment")
            return True
        elif ((status == 'active') & active):
            print("active")
            return True
        elif ((status == 'finished') & finished):
            print("finish")
            return True
    return func



def participate(request):
    id = request.GET["challenge"]
    ch = Challenge_article.objects.get(id=id)
    user = User_data.objects.get(user=request.user)

    link = Challenge_to_User(user=user, challenge=ch, role="participant")
    link.save()

    return HttpResponse(request.GET["challenge"])


def index(request):
    count = Challenge_article.objects.count()
    return render(request, "main/index.html", {'challenges_count':count})


def helper(request):
    return render(request, "main/help.html")


def detail(request, challenge_article_id):
    try:
        a = Challenge_article.objects.get(id=challenge_article_id)
    except:
        raise HttpResponseNotFound()
    return render(request, "main/details.html", {"article": a})


def challenge(request, id):
    args = {}
    try:
        ch = Challenge_article.objects.get(id=id)
    except:
        return HttpResponseNotFound()
    args["pub_date"] = ch.pub_date
    args["start_date"] = ch.start_date
    args["recruitment_time"] = ch.recruitment_time
    args["creator"] = ch.challenge_to_user_set.get(role="creator").user
    args["title"] = ch.article_title
    args["description"] = ch.article_description
    args["avatar_url"] = ch.avatar
    args["participants"] = ch.challenge_to_user_set.all()
    args["challenge_status"] = get_challenge_status(ch).value
    args["challenge_status_en"] = get_challenge_status(ch).name
    args["id"] = id
    if request.user.is_authenticated:
        user = User_data.objects.get(user=request.user)
        isparticipated = Challenge_to_User.objects.filter(
            challenge=ch, user_id=user.id
        ).all()
        if isparticipated.count() == 0 :
            args["isparticipated"] = False
        elif isparticipated[0].role == 'banned':
            args["isparticipated"] = 'banned'
        else:
            args["isparticipated"] = True
        
        if isparticipated.count() != 0:
            args["user_role"] = ch.challenge_to_user_set.get(user=user).role


    else:
        args["isparticipated"] = False

    return render(request, "main/challenge.html", args)


def get_challenge_status(challenge):
    """if (
    timezone.now() >= challenge.start_date
    and (timezone.now() - challenge.start_date).days >= challenge.recruitment_time
    ):
    """
    if (timezone.now() - challenge.start_date).days >= challenge.recruitment_time:
        return ChallengeStatus.finished
    elif timezone.now() >= challenge.start_date:
        return ChallengeStatus.active
    else:
        return ChallengeStatus.recruitment


def delete_challenge(request):
    if request.POST:
        Challenge_article.objects.get(id=request.POST["id"]).challenge_to_user_set.all().delete()
        Challenge_article.objects.get(id=request.POST["id"]).delete()
        return redirect('/catalog/')
    else:
        return HttpResponseNotFound()

def kick_user(request):
    if request.POST:
        challenge = Challenge_article.objects.get(id=request.POST['challengeid'])
        connector = request.user.user_data.challenge_to_user_set.get(challenge=challenge)
        if (
            (connector.role == "creator") &
            (connector.user == request.user.user_data) &
            (connector.challenge == challenge)
        ):
            user_for_kick = User_data.objects.get(user=request.POST['userid'])
            connector_user = challenge.challenge_to_user_set.get(user=user_for_kick)
            connector_user.role = 'banned'
            connector_user.save()
            return HttpResponse(status=200)
        else:
            return HttpResponse(status=401)

    return HttpResponse(status=500)


class ChallengeStatus(Enum):
    recruitment = "Идет набор"
    active = "Активный"
    finished = "Завершен"

artfreedom/apps/userprofile/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.contrib.auth.models import User
from django.forms import ModelForm
from main.models import Challenge_article, Challenge_to_User, User_data, Image
from django.utils.timezone import datetime
from django import forms
from django.contrib import messages



# Create your views here.

def myprofile(request):
    args = {}
    if request.user.is_authenticated:
        args['username'] = request.user.username
        usr = User.objects.get(id=request.user.id)
        userdata = User_data.objects.get(user=usr)
        args['status'] = userdata.status
        args['contacts'] = userdata.contacts

        args['col_challenges'] = userdata.challenge_to_user_set.count()
        #args['challenges'] = userdata.challenge_to_user_set.all()
        challenges = get_challenges_set(userdata)
        args['challenges'] = challenges

        args['ismyprofile'] = True

        if userdata.avatar != "":
            args['avatar_url'] = userdata.avatar
    else:
        return Http404()


        
    return render(request, "userprofile/profile.html", args)

def get_challenges_set(userdata):
        chs = userdata.challenge_to_user_set.all()
        res = []
        for c in chs:
            res.append({
            "challenge":c.challenge,
            "active":c.challenge.is_challenge_active(),
            "role": c.role,
            })
        return res


def profile(request, userid):
    args = {}
    if userid == request.user.id:
        return HttpResponseRedirect("/profile/")

    usr = User.objects.get(id=userid)
    userdata = User_data.objects.get(user=usr)
    args["username"] = usr.username
    args['status'] = userdata.status
    args['contacts'] = userdata.contacts
    args['col_challenges'] = userdata.challenge_to_user_set.count()
    args['challenges'] = get_challenges_set(userdata)

    if userdata.avatar != "":
        args['avatar_url'] = userdata.avatar
    args['ismyprofile'] = request.user.id == userid


    return render(request, "userprofile/profile.html", args)

def add_new_challenge(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("/profile/")
    if request.method == "POST":
        start_date = datetime.strptime(request.POST['start_date'], "%Y-%m-%d")
        challenge = Challenge_article(article_title=request.POST['article_title'],
        article_description=request.POST['article_description'],
        start_date=start_date,
        recruitment_time=request.POST['recruitment_time'])
        challenge.pub_date = datetime.now()
        """form = newImage(request.POST, request.FILES)

        if form.is_valid():
            print("valid")
            image = form.save(commit=False)
            image.author = request.user.user_data
            image.save()
            challenge.avatar = image
        else:
            default = Image.objects.get(image="images/1/image_izukits_21.jpg")
            challenge.avatar = default
            print("invalid")
        """
        challenge.save()
        ch_ = Challenge_to_User(user=request.user.user_data,
            challenge=challenge, role='creator')
        ch_.save()
        messages.success(request, "Челлендж успешно добавлен")
        return HttpResponseRedirect("/profile")
    else:
        return render(request, "userprofile/newchallenge.html")

class NewChallengeForm(ModelForm):
    class Meta:
        model = Challenge_article
        exclude = ['pub_date']

class newImage(ModelForm):
    class Meta:
        model = Image
        fields = ['image']

artfreedom/templates/loginsys/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/sing_page.css' %}">
<link rel="stylesheet" href="{% static 'css/text.css' %}">
{% endblock %}
{% block main_content %}
<main>
    <section class="form_wrapper">
        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <label for="login">Логин</label>
            <input type="text" id="login" name="username">
            <label for="password">Пароль</label>
            <input type="password" id="password" name="password">
            {% if login_error %}
            <label class="error">{{login_error}}</label>
            {% endif %}
            <input type="submit" value="Войти" class="log_button">
        </form>
        <p style="text-align: center;"> или </p>
        <a  class="log_button" style="text-align: center; display: block;" href="{% url 'registration' %}">
            Зарегестрироваться 
        </a>
    </section>
</main>
{% endblock %}

artfreedom/templates/loginsys/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Регистрация{% endblock %}
{% block styles %}<link rel="stylesheet" href="{% static 'css/sing_page.css' %}">{% endblock %}
{% block main_content %}
<main>
    <section class="form_wrapper">
        <form action="/registration/" method="POST" id="registration_form">
            {% csrf_token %}
            <label for="id_login">Логин</label>
            <p class="mini_text"> Только латинские буквы или цифры</p>
            {{form.login}}
            <div id='login_error'>Логин должен содержать только латинские буквы или цифры</div>
            <label for="id_password">Пароль</label>
            <p class="mini_text"> Только латинские буквы или цифры. Не менее 8 символов</p>

            {{form.password}}
            <div id='password_error'></div>
            <label for="id_password2">Повторите пароль</label>
            {{form.password2}}
            <div id='password2_error'></div>
            <label for="id_contact">E-mail или ссылка на соцсети (так с вами могут связаться другиме пользователи)</label>
            {{form.contact}}
            <div id='contacts'></div>
            <input type="submit" value="Зарегестрироваться" class="log_button">
        </form>
    </section>
    {% block messages %}


    {% endblock %}
</main>
{% endblock %}
{% block scripts %}
<script>
    is_login_valid = false
    is_password_valid = false
    is_password2_valid = false
    is_contacts_valid = false 

    elem_login = $('input[name=login]')
    elem_password = $('#id_password')
    elem_password2 = $('#id_password2')
    elem_contact = $('#id_contact')

    reg = "^[\da-zA-Z0-9]+$"
    elem_login.change(validate_login)
    elem_password.change(validate_password)
    elem_password2.change(validate_password2)
    elem_contact.change(validate_contacts)

    $("#registration_form").submit(function(){
        validate_login();
        validate_password();
        validate_contacts();
        validate_password2();

        is_login_valid = true
        is_password_valid = true
        is_password2_valid = true
        is_contacts_valid = true 

        if(is_login_valid&&is_password_valid&&is_password2_valid&&is_contacts_valid){
            return true
        }
        else{
            return false
        }
    }
    )

    function validate_login(){
        if(elem_login.val() == 0){
            $('#login_error').text("Поле не может быть пустым")
            $('#login_error').slideDown(300)
            is_login_valid = false
        }
        else if(elem_login.val().match(reg) == null){
            $('#login_error').text("Логин должен содержать только латинские буквы или цифры")
            $('#login_error').slideDown(300)
            is_login_valid = false
        }
        else{
            $('#login_error').slideUp(300)
            is_login_valid = true
        }
    }
     
    function validate_password(){
        if(elem_password.val() == 0){
            $('#password_error').text("Поле не может быть пустым")
            $('#password_error').slideDown(300)
            is_password_valid = false
        }
        else if(elem_password.val().match(reg) == null){
            $('#password_error').text("Пароль должен содержать только латинские буквы или цифры")
            $('#password_error').slideDown(300)
            is_password_valid = false
        }
        else if(elem_password.val().length < 8){
            $('#password_error').text("Пароль должен быть не менее 8 символов")
            $('#password_error').slideDown(300)
            is_password_valid = false
        }
        else{
            $('#password_error').slideUp(300)
            is_password_valid = true
        }
    }
    function validate_password2(){
        if(elem_password2.val() == 0){
            $('#password2_error').text("Поле не может быть пустым")
            $('#password2_error').slideDown(300)
            is_password2_valid = false
        }
        else if(elem_password2.val() != elem_password.val()){
            $('#password2_error').text("Пароли не совпадают")
            $('#password2_error').slideDown(300)
            is_password2_valid = false
        }
        else{
            $('#password2_error').slideUp(300)
            is_password2_valid = true
        }
    }
    function validate_contacts(){
        if(elem_contact.val() == 0){
            $('#contacts').text("Поле не может быть пустым")
            $('#contacts').slideDown(300)
            is_contacts_valid = false
        }
        else{
            $('#contacts').slideUp(300)
            is_contacts_valid = true
        }
    }
</script>
{% endblock %}